import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import styleContacto from "../styles/styleContacto.module.css";
// import globals from "../styles/globals.css";

const contacto = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        <main className="mainContacto">
          <h1>Contacta a un Ejecutivo de ModelHome</h1>

          <form action="contacto.html">
            <fieldset>
              <legend>Datos Personales</legend>
              <div>
                <label for="nombre">Nombre</label>
                <input type="text" id="nombre" name="nombre" />
                <span></span>
              </div>
              <div>
                <label for="rut">RUT</label>
                <input
                  type="text"
                  id="rut"
                  name="rut"
                  placeholder="12345678-5"
                />
                <span></span>
              </div>
              <div>
                <label for="tel">Teléfono</label>
                <input type="text" id="tel" name="telefono" />
                <span></span>
              </div>
            </fieldset>
            <fieldset>
              <legend>Ubicación</legend>
              <div>
                <label for="direccion">Dirección</label>
                <input type="text" id="direccion" name="direccion" />
                <span></span>
              </div>
              <div>
                <label for="comuna">Comuna</label>
                <select name="comuna" id="comuna">
                  <option value="">-- Por favor escoja una opción--</option>
                  <option value="santiago">Santiago</option>
                  <option value="providencia">Providencia</option>
                  <option value="la-florida">La Florida</option>
                  <option value="las-condes">Las Condes</option>
                  <option value="vitacura">Vitacura</option>
                </select>
                <span></span>
              </div>
            </fieldset>
            <div class="botones">
              <button class="boton bg-success submit" type="submit">
                Enviar
              </button>
              <button class="boton bg-warning reset" type="reset">
                Limpiar
              </button>
            </div>
          </form>
        </main>
      </Layout>
    </>
  );
};

export default contacto;

/*import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import styleContacto from "../styles/styleContacto.module.css";
// import globals from "../styles/globals.css";

const contacto = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        <main className={styleContacto.mainContacto}>
          <h1>Contacta a un Ejecutivo de ModelHome</h1>

          <form action="contacto.html" className={styleContacto.formContacto}>
            <fieldset className={styleContacto.formContactoFieldset}>
              <legend className={styleContacto.formContactoFieldsetLegend}>
                Datos Personales
              </legend>
              <div className={styleContacto.formContactoFieldsetDiv}>
                <label
                  for="nombre"
                  className={styleContacto.formContactoFieldsetDivLabel}
                >
                  Nombre
                </label>
                <input type="text" id="nombre" name="nombre" />
                <span className={styleContacto.formContactoSpan}></span>
              </div>
              <div className={styleContacto.formContactoFieldsetDiv}>
                <label
                  for="rut"
                  className={styleContacto.formContactoFieldsetDivLabel}
                >
                  RUT
                </label>
                <input
                  type="text"
                  id="rut"
                  name="rut"
                  placeholder="12345678-5"
                />
                <span></span>
              </div>
              <div className={styleContacto.formContactoFieldsetDiv}>
                <label
                  for="rut"
                  className={styleContacto.formContactoFieldsetDivLabel}
                >
                  Teléfono
                </label>
                <input type="text" id="telefono" name="telefono" />
                <span className={styleContacto.formContactoSpan}></span>
              </div>
            </fieldset>
            <fieldset>
              <legend className={styleContacto.formContactoFieldsetLegend}>
                Ubicación
              </legend>
              <div className={styleContacto.formContactoFieldsetDiv}>
                <label
                  for="direccion"
                  className={styleContacto.formContactoFieldsetDivLabel}
                >
                  Dirección
                </label>
                <input type="text" id="direccion" name="direccion" />
                <span></span>
              </div>
              <div className={styleContacto.formContactoFieldsetDiv}>
                <label
                  for="comuna"
                  className={styleContacto.formContactoFieldsetDivLabel}
                >
                  Comuna
                </label>
                <select name="comuna" id="comuna">
                  <option value="">-- Por favor escoja una opción--</option>
                  <option value="santiago">Santiago</option>
                  <option value="providencia">Providencia</option>
                  <option value="la-florida">La Florida</option>
                  <option value="las-condes">Las Condes</option>
                  <option value="vitacura">Vitacura</option>
                </select>
                <span></span>
              </div>
            </fieldset>
            <div class="botones">
              <button
                type="submit"
                className={`${styleContacto.boton} ${styleContacto.bgSuccess}`}
              >
                Enviar
              </button>
              <button
                type="reset"
                className={`${styleContacto.boton} ${styleContacto.bgWarning}`}
              >
                Limpiar
              </button>
            </div>
          </form>
        </main>
      </Layout>
    </>
  );
};

export default contacto;
 */
