import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import styleContacto from "../styles/styleContacto.module.css";
import houseForm from "../public/img/house-form.png";

// import globals from "../styles/globals.css";

const registro = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        <div class="form-container">
          <div class="form-img">
            <Image
              height={241}
              width={322}
              src={houseForm}
              alt="Modelo de casa"
              className="form-img01"
            />
          </div>
          <div class="div-form">
            <h2>
              Regista tu interés en <strong>ModelHome</strong>
            </h2>
            <form action="contacto.html" class="form-container2">
              <fieldset>
                <p>Datos personales</p>
                <div>
                  <label for="nombre">Nombre:</label>
                  <input type="text" name="nombre" id="" />
                </div>
                <div>
                  <label for="email">Email</label>
                  <input type="text" id="email" name="email" />
                </div>
                <div>
                  <label for="contrasena">Contraseña</label>
                  <input type="password" id="contrasena" name="contrasena" />
                </div>
                <div class="botones">
                  <button class="boton bg-success submit" type="submit">
                    Registrar
                  </button>
                </div>
              </fieldset>
            </form>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default registro;
